eprobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  left_steer_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_steer_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_steer_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_steer_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Velocity Controllers ---------------------------------------
  left_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_front_wheel_joint
    pid: {p: 10.0, i: 0.5, d: 0.0, i_clamp: 0.0}  # 1 0 0
  right_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_front_wheel_joint
    pid: {p: 10.0, i: 0.5, d: 0.0, i_clamp: 0.0}  # 1 0 0

  gazebo_ros_control:
    pid_gains:
      left_steer_joint:
        p: 100.0
        i: 0.01
        d: 10.0
      right_steer_joint:
        p: 100.0
        i: 0.01
        d: 10.0
      left_front_wheel_joint:
        p: 10.0
        i: 0.5
        d: 0.0
        i_clamp: 0.0
      right_front_wheel_joint:
        p: 10.0
        i: 0.5
        d: 0.0
        i_clamp: 0.0
